name: Frontend CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
    - main

env:
  NodeVersion: 20.19.1

jobs:
  js-ci:
    runs-on: ubuntu-latest
  defaults:
    run:
      working-directory: ./frontend

  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NodeVersion }}
        cache: npm

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test

    - name: Linting
      run: npm run lint

    - name: Build
      run: npm run build

    - name: Upload Frontend artifacts
      uses: actions/upload-artifact@v4
      with:
        name: frontend-artifacts
        path: .