name: Backend CI/CD Production

on:
  push:
    branches:
      - main
  pull_request:
    branches:
    - main

env:
  PythonVersion: 3.11.9

jobs:
  ci_pipeline_prod:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PythonVersion }}

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install coverage flake8
          pip install -r requirements.txt

      - name: Run tests
        run: |
          source venv/bin/activate
          python manage.py test

      - name: Generate Report
        run: |
          source venv/bin/activate
          coverage run --source='.' manage.py test
          coverage report

      - name: Linting
        run: |
          source venv/bin/activate
          flake8 . --show-source --statistics --exit-zero

      - name: Check Complexity
        run: |
          source venv/bin/activate
          flake8 . --exit-zero --max-complexity=6

      - name: Upload python artifacts
        uses: actions/upload-artifact@v4
        with:
          name: python-artifacts
          path: ./backend
#-------------------
  cd_pipeline_prod:
    runs-on: ubuntu-latest
    needs: ci_pipeline_prod

    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download backend artifacts
        uses: actions/download-artifact@v4
        with:
          name: backend-artifacts
          path: ./backend

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'culinary-backend-app-production'
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE_BACKEND_PROD }}
          package: ./backend